title: Sailing Scoreboard Docs
logo: "/images/ssblogo-h.png"
description: User documentation for Sailing Scoreboard
theme: just-the-docs

url: https://hjelliott.github.io/ssbdocs

aux_links:
  Sailing Scoreboard: https://www.sailingscoreboard.com/workbench/
